defaults:
  - _self_
  - openretina@model_configs: hoefling_2024_core_readout_low_res
  - openretina/mei_generation: mei_generation

data_subfolders:
  day: 20250903
  experiment: 1

DJ:
  username: ssuhai
  userinfo:
    experimenter: 'closedlooptest' 
    # at what location what experimental information is stored in the file name
    animal_loc: 1
    region_loc: 2
    field_loc: 3
    stimulus_loc: 4 
    cond1_loc: 5
    data_dir: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/data/recordings/test_meis_1

  table_parameters:
    # for the DJ tables 
    PreprocessParams: [
        {preprocess_id: 1, fs_resample: 60, stim_names: ["gChirp", "lChirp", "movingbar", "densenoise"]},
        {preprocess_id: 2, window_length: 60, poly_order: 3, non_negative: 1, subtract_baseline: 0, standardize: 1, stim_names: ["mouse_cam"]}
        ]
      # for janes densenoise (requires 60 hz trace sampling, dont know why ...)
      # fs_resample: 60
      

      # # Below the values for spike estimation I think
      # window_length: 60  # default
      # poly_order: 3  # default
      # non_negative: 1,  # non default
      # subtract_baseline: 0  # non default
      # standardize: 1  # default

    Stimulus:
      noise:
        stim_name: 'densenoise'
        stim_family: 'noise'
        pix_n_x: 20
        pix_n_y: 15
        skip_duplicates: True
        pix_scale_x_um: 40
        pix_scale_y_um: 40
        framerate: 5

    DNoiseTraceParams:
        dnoise_params_id: 1
        fupsample_trace: 20
        fupsample_stim: 4
        ref_time: 'stim'
        fit_kind: 'gradient'
        skip_duplicates: True
        pre_blur_sigma_s: 0.
        post_blur_sigma_s: 0.




paths: 
  # absolute paths: change these to your own
  repo_directory: /gpfs01/euler/User/ssuhai/GitRepos/simulation_closed_loop/
  home_directory: /gpfs01/euler/User/ssuhai
  dj_config_directory: datajoint 
  rgc_output_directory: datajoint/rgc_classifier # dir where classifier should be stored
  recording_files_dir: /gpfs01/euler/data/Data/Suhai/move_closed_loop_data_here # /gpfs01/euler/data/Data/Suhai/test_data_klaudia # 
  stimulus_output_dir: /gpfs01/euler/data/Data/Suhai/stimuli_closed_loop
  dummy_ini_dir: data/dummy_ini/


quality_filtering:
  chirp_qi_min: 0.35
  d_qi_min: 0.6 
  celltypes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
  classifier_confidence: 0.25
  rf_qidx_min: 0.5
  min_testset_correl: 0.3 # at wat correl to include in mei analysis


debug: False
plot_results: True
clean_up_before: True
clean_up_after: False
