defaults:
  - preprocessors: preprocessors
  - models: models
  - recorders: recorders
  - stimulators: stimulators

# stimulus informaiton 
stimulus_type: noise
stimulus_file_path: GitRepos/simulation_closed_loop/data/stimuli/original/noise.h5